mode = "light"
name = "Catppuccin Latte"
background = "#eff1f5"
surface = "#ccd0da"
overlay = "#bcc0cc"
text = "#4c4f69"
subtext = "#6c6f85"
accent = "#8839ef"
green = "#40a02b"
yellow = "#df8e1d"
red = "#d20f39"
