[keybindings]
"Alt+Space" = "launcher toggle"
"Alt+Shift+Space" = "meta toggle"
"Alt+Enter" = "spawn terminal"
"Alt+F" = "window toggle-fullscreen"
"Alt+T" = "window set-tiling"
"Alt+Shift+T" = "window toggle-float"
"Alt+Q" = "window close"
"Alt+S" = "workspace next-active"
"Alt+D" = "workspace recent"
"Alt+Shift+R" = "config reload"
"Super+Shift+S" = "screenshot"
"Alt+H" = "window focus left"
"Alt+Shift+H" = "window move left"
"Alt+Left" = "window focus left"
"Alt+Shift+Left" = "window move left"
"Alt+J" = "window focus down"
"Alt+Shift+J" = "window move down"
"Alt+Down" = "window focus down"
"Alt+Shift+Down" = "window move down"
"Alt+K" = "window focus up"
"Alt+Shift+K" = "window move up"
"Alt+Up" = "window focus up"
"Alt+Shift+Up" = "window move up"
"Alt+L" = "window focus right"
"Alt+Shift+L" = "window move right"
"Alt+Right" = "window focus right"
"Alt+Shift+Right" = "window move right"
"Alt+1" = "workspace 1"
"Alt+Shift+1" = "window move-workspace 1 --follow"
"Alt+2" = "workspace 2"
"Alt+Shift+2" = "window move-workspace 2 --follow"
"Alt+3" = "workspace 3"
"Alt+Shift+3" = "window move-workspace 3 --follow"
"Alt+4" = "workspace 4"
"Alt+Shift+4" = "window move-workspace 4 --follow"
"Alt+5" = "workspace 5"
"Alt+Shift+5" = "window move-workspace 5 --follow"
"Alt+6" = "workspace 6"
"Alt+Shift+6" = "window move-workspace 6 --follow"
"Alt+7" = "workspace 7"
"Alt+Shift+7" = "window move-workspace 7 --follow"
"Alt+8" = "workspace 8"
"Alt+Shift+8" = "window move-workspace 8 --follow"
"Alt+9" = "workspace 9"
"Alt+Shift+9" = "window move-workspace 9 --follow"
